version: '3.8'

services:
  # Приложение для разработки
  app:
    build:
      context: .
      target: base
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/deadline
      - REDIS_URL=redis://redis:6379
      - BETTER_AUTH_SECRET=dev-secret-key
      - BETTER_AUTH_URL=http://localhost:3000
      - GIGACHAT_API_KEY=${GIGACHAT_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    depends_on:
      - db
      - redis
    restart: unless-stopped
    command: npm run dev

  # База данных для разработки
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: deadline
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Redis для разработки
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped

  # Drizzle Studio для работы с БД
  drizzle-studio:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4983:4983"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/deadline
    command: npx drizzle-kit studio --host 0.0.0.0 --port 4983
    depends_on:
      - db

volumes:
  postgres_dev_data:
  redis_dev_data:
